### ISSUE TITLE
Is it possible to Include a Custom Button on the ToolBar

### ISSUE THREAD

**Issue by rahulr-ey** [kolkov/angular-editor#252]
My requirement is that I need a custom button on the toolbar, while clicking on that button a dropdown list should come with a particular set of values that I need to use as placeholders in the body during the html generation

**Comment by rahulr-ey** [comment]
@kolkov  can u help

**Comment by alexgurrola** [comment]
@kolkov I need a single button in the toolbar as well, but I don't see any option of it.

**Comment by alexgurrola** [comment]
@rahulr-ey I found an older issue which indicates it may be a while before we have custom button functionality. https://github.com/kolkov/angular-editor/issues/62

**Comment by alexgurrola** [comment]
I may just fork this and create something extremely basic for my purposes.

**Comment by embu18** [comment]
@kolkov the same issue.

**Comment by paddotk** [comment]
Seems like a very specific use-case thing. I'd suggest to manually add a button positioned over the editor.
``` jsx
<div class="wrapper">
  <button class="my-custom-button">Do something</button>
  <angular-editor></angular-editor>
</div>
```

``` css
.wrapper {
  position: relative;
}
.my-custom-button {
  position: absolute;
  top: 10px;
  right: 10px;
  z-index: 2;
}
angular-editor {
  position: relative;
  z-index: 1;
}
```
