### ISSUE TITLE
Firefox align

### ISSUE THREAD

**Issue by cristiansandru11** [kolkov/angular-editor#41]
Hi, please have a look at this:
[printscreen](https://imgur.com/P34ojZR)

**the cursor is not aligned with the text box.**
If I write something inside of it, it's working as expected.
The issue is present also on your [example](https://angular-editor-wysiwyg.stackblitz.io/)

**Comment by iwnow** [comment]
the issue is on .angular-editor-textarea::before element need to set display: inline;
```css
.angular-editor-textarea::before {
display: inline;
}
```
