### ISSUE TITLE
Is there an option to have a full screen toggle?

### ISSUE THREAD

**Issue by rvwoezik** [kolkov/angular-editor#437]
Or can someone point me in the right direction?

**Comment by kolkov** [comment]
Thank you for the question! Fullscreen mode is being tracked in #545 (Table and Fullscreen features).

**Current Status:**
Angular Editor doesn't have a built-in fullscreen toggle button.

**Workaround - Implement Your Own:**

```html
<div [class.fullscreen]="isFullscreen">
  <angular-editor [config]="editorConfig">
    <ng-template #customButtons let-executeCommandFn="executeCommandFn">
      <ae-toolbar-set>
        <button aeButton 
                title="Toggle Fullscreen" 
                (click)="toggleFullscreen()">
          {{ isFullscreen ? '⛶' : '⛶' }}
        </button>
      </ae-toolbar-set>
    </ng-template>
  </angular-editor>
</div>
```

```typescript
export class MyComponent {
  isFullscreen = false;

  toggleFullscreen() {
    this.isFullscreen = !this.isFullscreen;
  }
}
```

```css
.fullscreen {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 9999;
  background: white;
  padding: 20px;
}

.fullscreen angular-editor {
  height: calc(100vh - 100px);
}
```

**Or use native Fullscreen API:**

```typescript
toggleFullscreen() {
  const elem = document.querySelector('.editor-container') as any;
  
  if (!document.fullscreenElement) {
    elem.requestFullscreen();
  } else {
    document.exitFullscreen();
  }
}
```

**Feature Request:**
Fullscreen support is tracked in #545. If you'd like this as a built-in feature, please add your use case there.

Closing as duplicate of #545.
