### ISSUE TITLE
Angular editor font selection not working inside angular material modal please help

### ISSUE THREAD

**Issue by niloyvu** [kolkov/angular-editor#445]
"dependencies": {
    "@angular/animations": "~11.2.11",
    "@angular/cdk": "^11.2.10",
    "@angular/common": "~11.2.11",
    "@angular/compiler": "~11.2.11",
    "@angular/core": "~11.2.11",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "~11.2.11",
    "@angular/material": "^11.2.10",
    "@angular/platform-browser": "~11.2.11",
    "@angular/platform-browser-dynamic": "~11.2.11",
    "@angular/router": "~11.2.11",
    "@kolkov/angular-editor": "^1.1.4",
    "@swimlane/ngx-charts": "^19.2.0",
    "jwt-decode": "^3.1.2",
    "lodash": "^4.17.21",
    "ngx-skeleton-loader": "^2.9.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.10",
    "@angular/cli": "~11.2.10",
    "@angular/compiler-cli": "~11.2.11",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"

**Comment by srikarthikjoy** [comment]
@niloyvu I have posted comments on issue #499. Please refer to them for more information.

**Comment by kolkov** [comment]
Thank you for reporting this! This is a **z-index conflict** between Angular Material dialog and the Angular Editor dropdown.

**Root Cause:**
Angular Material dialogs have high z-index (1000+), and the editor's dropdown appears behind the modal overlay.

**Solutions:**

**1. CSS Fix - Increase Dropdown Z-Index:**
```css
/* In your global styles.scss or component styles */
::ng-deep .angular-editor .ae-picker-options {
  z-index: 10000 !important; /* Higher than mat-dialog (1000) */
}
```

**2. Material Dialog Configuration:**
When opening the dialog, disable overlay:
```typescript
this.dialog.open(YourDialogComponent, {
  hasBackdrop: true,
  disableClose: false,
  // This helps with z-index stacking
  panelClass: 'custom-dialog-container'
});
```

Then in styles:
```css
.custom-dialog-container .mat-dialog-container {
  position: relative;
  z-index: 1000;
}

.angular-editor .ae-picker-options {
  z-index: 1001;
}
```

**3. Use cdkDropdown (Better Solution):**
The editor's custom select might benefit from using Angular CDK Overlay, which handles z-index stacking contexts properly.

**Note about your version:**
You're using Angular 11 + angular-editor 1.1.4. Consider upgrading to:
- **Angular Editor v3.0+** (requires Angular 20+)
- **Angular Editor v2.0+** (supports Angular 13-19)

The CSS fix should work for v1.1.4 as well.

**Quick Fix for Testing:**
```css
/* In your component SCSS with ::ng-deep */
::ng-deep {
  .angular-editor .ae-font-name,
  .angular-editor .ae-font-size,
  .angular-editor ae-select {
    z-index: 9999 !important;
  }
}
```

Closing as this is a CSS z-index issue with a known workaround. This is a common issue when using editors inside modals/dialogs across different UI frameworks.
