### ISSUE TITLE
Anyway to change button names?

### ISSUE THREAD

**Issue by phlaidback** [kolkov/angular-editor#523]
Is there any way to translate the button names to an other language?

Regards
/ Pontus

**Comment by kolkov** [comment]
Сейчас нет встроенной локализации, но есть простой workaround через CSS:

```css
/* Hide original tooltips */
[aeButton] {
  pointer-events: none;
}

[aeButton]::after {
  content: attr(data-tooltip);
  pointer-events: auto;
}
```

Либо можно использовать Angular i18n, но это требует билда для каждого языка.

**Feature request:** Добавил в backlog задачу на i18n поддержку для v3.2+. Будет что-то типа:
```typescript
config = {
  i18n: {
    bold: 'Fett',
    italic: 'Kursiv',
    // ...
  }
}
```
