### ISSUE TITLE
how to make the text color picker stay below the button

### ISSUE THREAD

**Issue by VoBaQuan** [kolkov/angular-editor#576]
![Image](https://github.com/user-attachments/assets/51bdea86-746b-4a99-9841-41d0fbc7f226)

**Comment by kolkov** [comment]
Thanks for reporting!

**Solution found** by @RenishSkills in wfpena's fork:
https://github.com/wfpena/angular-wysiwyg/pull/38/commits/b7af7de5842893efa23a6526832c32e5292af32e

The fix involves adding proper positioning styles to the color picker.

**Workaround for now:**
```css
angular-editor ::ng-deep input[type='color'] {
  position: absolute;
  top: 100%;
  left: 0;
}
```

Will consider integrating this fix in v3.2+.

Questions? New issue welcome!
